wand-item:
  ==: org.bukkit.inventory.ItemStack
  v: 2230
  type: STICK
  meta:
    ==: ItemMeta
    meta-type: UNSPECIFIC
    display-name: 'Wand'
    lore:
      - 'Creates selections'
caching:
  rpkit_selection:
    minecraft_profile_id:
      enabled: true
      size: 20